server:
  port: 8080

spring:
  datasource:
    platform: mariadb
    url: jdbc:mariadb://localhost:3306/barkeeper-database
    username: root
    password: root
    drivenClassName: org.mariadb.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddlAuto: create-drop

